package top.simba1949.mapper;

import java.util.List;
import top.simba1949.common.SysUser;

public interface SysUserMapper {
    /**
     * 通过 resultMap 设置 association 跨 XML 查询
     * @return
     */
    List<SysUser> selectSysUserViaResultMapAssociationResultMap();
    /**
     * 通过 resultMap 设置 association 简单查询
     * @return
     */
    List<SysUser> selectSysUserViaResultMapAssociation();
    /**
     * 通过简单的 resultMap 设置查询
     * @return
     */
    List<SysUser> selectSysUserViaResultMapSimple();
    /**
     * 通过别名查询
     * @return
     */
    List<SysUser> selectSysUserViaTypeAliases();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    SysUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    List<SysUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysUser record);
}